export const getChatMessagesResp = {
  docs: [
    {
      _id: 'string',
      text: 'Hello',
      user_id: 'string',
      group_id: 'string',
      send_at: '2023-04-15T11:48:49.442Z',
      __v: 0,
      sentByMe: 'NO',
    },
    {
      _id: 'string',
      text: 'string',
      user_id: 'string',
      group_id: 'string',
      send_at: '2023-04-14T12:12:06.714Z',
      __v: 0,
      sentByMe: 'NO',
    },
    {
      _id: 'string',
      text: 'jj',
      user_id: 'string',
      group_id: 'string',
      send_at: '2023-04-13T10:50:33.992Z',
      __v: 0,
      sentByMe: 'NO',
    },
  ],
  totalDocs: 34,
  limit: 30,
  totalPages: 2,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: true,
  prevPage: null,
  nextPage: 2,
};
